<a href="https://colab.research.google.com/github/elandverymuchnothing/Capstone_2/blob/main/lastname_sales_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
#My name Is Ariel Rollins; my Sales Manager is See Ellefson and New York is the state territory I will analyze.

In [77]:
#Data Analyis Library Import

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Below, 'Store Sales' are defined.

In [78]:
# Defining Store Sales
store_sales = pd.read_csv('StoreSales.csv')

# Display the output
display(store_sales)

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
0              1/1/2022       702        NaN   105349-M         8.00
1              1/1/2022       704        NaN   105350-T       144.00
2              1/1/2022       705        NaN   105351-M        44.00
3              1/1/2022       705        NaN   105352-M        47.61
4              1/1/2022       705        NaN   105353-A        20.36
...                 ...       ...        ...        ...          ...
335124       12/31/2025       909        NaN   105353-A        20.36
335125       12/31/2025       909      332.0   105364-S        17.70
335126       12/31/2025       910        NaN   105672-B        26.52
335127       12/31/2025       910        NaN   105653-M        11.00
335128       12/31/2025       910        NaN  105300-IT        77.81

[335129 rows x 5 columns]

In [79]:
# Imported Customer List
customers_df = pd.read_csv('customer_list.csv')

# Dataset information
customers_df.info()

#Display the output
display(customers_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    object
dtypes: object(1)
memory usage: 4.2+ KB

       cust_id|date|time|name|email|phone|sms-opt-out
0    1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1    2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2    3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3    4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4    5|2023-11-18|14:22:10|Joey|howyoudoing@central...
..                                                 ...
516  517|2024-02-15|11:30:30|Perry the Platypus|age...
517  518|2024-05-01|15:55:45|Baljeet|baljeet@danvil...
518  519|2023-03-05|09:20:00|Buford|buford@danville...
519  520|2023-05-18|13:45:15|Vanessa D.|vanessa@dan...
520  521|2023-08-01|18:10:30|Linda Flynn-Fletcher|l...

[521 rows x 1 columns]

In [80]:
# Imported Product Categories
products_categories_df = pd.read_csv('ProductCategories.csv')

# Dataset Information
products_categories_df.info

# Display the output
display(products_categories_df)

,CategoryID,Category,SubcategoryID,Subcategory
0,120,Technology & Accessories,120-tab,Tablets
1,120,Technology & Accessories,120-cal,Calculators
2,120,Technology & Accessories,120-sof,Software Download
3,120,Technology & Accessories,120-hea,Headphones
4,120,Technology & Accessories,120-ext,External Accessories
5,120,Technology & Accessories,120-cha,Chargers and Power Adapters
6,120,Technology & Accessories,120-lap,Laptops
7,130,Apparel and Merchandise,130-off,Office and Study Supplies
8,100,Textbooks,100-bus,Business & Economics
9,130,Apparel and Merchandise,130-clo,"Clothing (T-Shirts, Hoodies, and Jackets)"
10,130,Apparel and Merchandise,130-tec,Technology Accessories
11,115,Art Supplies,115-ske,Sketchbooks and Paper
12,125,Books (General),125-fic,Fiction
13,110,Stationery and Supplies,110-art,Art Supplies
14,100,Textbooks,100-mis,Miscellaneous Academic Topics
15,115,Art Supplies,115-kid,Kids Art Supplies
16,100,Textbooks,100-eng,Engineering & Technology
17,110,Stationery and Supplies,110-bin,Binders and Folders
18,100,Textbooks,100-hea,Health Sciences
19,100,Textbooks,100-tec,Technology and Computing
20,110,Stationery and Supplies,110-wri,Writing Instruments
21,100,Textbooks,100-soc,Social Sciences
22,110,Stationery and Supplies,110-des,Desk Accessories
23,100,Textbooks,100-lan,Language and Linguistics
24,130,Apparel and Merchandise,130-hom,Home and Decor
25,115,Art Supplies,115-mis,Miscellaneous Art Supplies
26,100,Textbooks,100-hum,Humanities
27,130,Apparel and Merchandise,130-hat,Hats and Caps
28,100,Textbooks,100-exa,Exam Prep and Study Guides
29,130,Apparel and Merchandise,130-mem,Memorabilia and Collectibles
30,115,Art Supplies,115-pai,Paint Brushes
31,130,Apparel and Merchandise,130-spo,Sports and Outdoor Gear
32,115,Art Supplies,115-scu,Sculpting Supplies
33,125,Books (General),125-stu,Study Guides
34,110,Stationery and Supplies,110-mis,Miscellaneous Supplies
35,115,Art Supplies,115-dra,Drawing and Sketching Tools
36,125,Books (General),125-non,Non-Fiction
37,110,Stationery and Supplies,110-pla,Planners and Calendars
38,115,Art Supplies,115-pai,Paints
39,115,Art Supplies,115-cal,Calligraphy and Lettering
40,110,Stationery and Supplies,110-not,Notebooks and Notepads
41,100,Textbooks,100-mat,Math and Statistics
42,110,Stationery and Supplies,110-adh,Adhesives and Tapes
43,110,Stationery and Supplies,110-org,Organization Supplies
44,100,Textbooks,100-sci,Science
45,130,Apparel and Merchandise,130-acc,Accessories
46,115,Art Supplies,115-cut,Cutting and Measuring Tools
47,110,Stationery and Supplies,110-pen,Pencils and Erasers
48,110,Stationery and Supplies,110-pap,Paper Products
49,125,Books (General),125-ref,Reference Materials
50,115,Art Supplies,115-pal,Palettes and Mixing Tools
51,115,Art Supplies,115-eas,Easels and Storage

In [81]:
# Import Products.csv
products_df = pd.read_csv('Products (1).csv')

# Dataset information
products_df.info()

# Display the output
display(products_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

      Prod Num                               Product  CategoryID SubcategoryID
0    105248-IT                      TCL NXTPAPER 10s         120       120-tab
1    105249-IT         Dell Latitude 7320 Detachable         120       120-tab
2    105250-IT                            Realme Pad         120       120-tab
3    105251-IT                    Lenovo Tab P12 Pro         120       120-tab
4    105252-IT               Microsoft Surface Pro 9         120       120-tab
..         ...                                   ...         ...           ...
664   105912-T               Networking Fundamentals         100       100-tec
665   105913-T             Introduction to Databases         100       100-tec
666  105914-IT    SanDisk Extreme Portable SSD (1TB)         120       120-ext
667   105915-M  LTCA Year Up Spiral Notebook (Black)         130       130-off
668   105916-M       LTCA Year Up Sunglasses (Black)         130       130-acc

[669 rows x 4 columns]

In [82]:
# Import Store Sales
sales_df = pd.read_csv('StoreSales.csv')

# View dataset information
sales_df.info()

#Display the output
display(sales_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
0              1/1/2022       702        NaN   105349-M         8.00
1              1/1/2022       704        NaN   105350-T       144.00
2              1/1/2022       705        NaN   105351-M        44.00
3              1/1/2022       705        NaN   105352-M        47.61
4              1/1/2022       705        NaN   105353-A        20.36
...                 ...       ...        ...        ...          ...
335124       12/31/2025       909        NaN   105353-A        20.36
335125       12/31/2025       909      332.0   105364-S        17.70
335126       12/31/2025       910        NaN   105672-B        26.52
335127       12/31/2025       910        NaN   105653-M        11.00
335128       12/31/2025       910        NaN  105300-IT        77.81

[335129 rows x 5 columns]

In [83]:
# Import Store Details
stores_df = pd.read_csv('StoreDetail.csv')

# Dataset information
stores_df.info()

#Display the output
display(stores_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

,Store Location,State,Store ID,Territory Manager,Region,Region Director
0,Aurora,Colorado,701,Jim Heck,West,Cassie Chambers
1,Berthoud,Colorado,702,Jim Heck,West,Cassie Chambers
2,Boulder,Colorado,703,Jim Heck,West,Cassie Chambers
3,Castle Rock,Colorado,704,Jim Heck,West,Cassie Chambers
4,Denver,Colorado,705,Jim Heck,West,Cassie Chambers
...,...,...,...,...,...,...
106,Dallas,Texas,907,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
107,Denton,Texas,908,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
108,Desoto,Texas,909,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
109,Fort Worth,Texas,910,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
110,Georgetown,Texas,911,"Jeff ""Howdy"" Richards",South,Andy Gisselquist

Who are the territory managers for the sales territories assigned? What are the store IDs and cities for the stores in each assigned sales territory?

In [84]:
# Stores for See Ellefson
see_stores = stores_df[
    stores_df["Territory Manager"] == "See Ellefson"]

# Displaying relevant columns
see_stores[
    ["Territory Manager", "Store ID", "Store Location"]]

#Store IDs range from 840-851 in numerical order, smallest to largest.
#The city locations for Stores 840-851 are listed as Albany, Buffalo, Elmira, Ithaca, Oswego, Plattsburgh, Poestenkill, Rochester, Syracuse, Brooklyn, New York, & Queens.

# Stores for Jeff "Howdy" Richards
richards_stores = stores_df[
    stores_df["Territory Manager"] == 'Jeff "Howdy" Richards']

# Displaying relevant columns
richards_stores[
    ["Territory Manager", "Store ID", "Store Location"]]

print("Stores for both See Ellefson's and Jeff 'Howdy' Richards'")

#Display the output
display(see_stores, richards_stores)

Stores for both See Ellefson's and Jeff 'Howdy' Richards'

   Store Location     State  Store ID Territory Manager Region Region Director
86         Albany  New York       840      See Ellefson   East      Ana Jilani
87        Buffalo  New York       841      See Ellefson   East      Ana Jilani
88         Elmira  New York       842      See Ellefson   East      Ana Jilani
89         Ithaca  New York       843      See Ellefson   East      Ana Jilani
90         Oswego  New York       844      See Ellefson   East      Ana Jilani
91    Plattsburgh  New York       845      See Ellefson   East      Ana Jilani
92    Poestenkill  New York       846      See Ellefson   East      Ana Jilani
93      Rochester  New York       847      See Ellefson   East      Ana Jilani
94       Syracuse  New York       848      See Ellefson   East      Ana Jilani
95       Brooklyn  New York       849      See Ellefson   East      Ana Jilani
96       New York  New York       850      See Ellefson   East      Ana Jilani
97         Queens  New York       851      See Ellefson   East      Ana Jilani

,Store Location,State,Store ID,Territory Manager,Region,Region Director
100,Arlington,Texas,901,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
101,Austin,Texas,902,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
102,Bacliff,Texas,903,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
103,Baytown,Texas,904,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
104,Beaumont,Texas,905,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
105,Cedar Park,Texas,906,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
106,Dallas,Texas,907,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
107,Denton,Texas,908,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
108,Desoto,Texas,909,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
109,Fort Worth,Texas,910,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
110,Georgetown,Texas,911,"Jeff ""Howdy"" Richards",South,Andy Gisselquist

What is monthly total revenue for in-store sales in each of the two sales territories, over the full
period covered by the data?

In [85]:
current_sales = sales_df.copy()
# Defining the current_sales

current_sales['Transaction Date'] = pd.to_datetime(current_sales['Transaction Date'])
current_sales['Month'] = current_sales['Transaction Date'].dt.to_period('M')
current_sales['Year'] = current_sales['Transaction Date'].dt.year
# Convert the date and create the 'Month' column

monthly_rev = (current_sales
               .groupby('Month')['Sale Amount']
               .sum()
               .reset_index())

monthly_rev = monthly_rev.rename (columns = {'Sale Amount': 'Monthly Revenue'})
# Group by the month and sum of the sales amount

display(monthly_rev)
# Display the output

      Month  Monthly Revenue
0   2022-01        610945.43
1   2022-02        622272.35
2   2022-03        660349.58
3   2022-04        650453.95
4   2022-05        681687.71
5   2022-06        658483.42
6   2022-07        689840.65
7   2022-08        671138.48
8   2022-09        596975.23
9   2022-10        671127.85
10  2022-11        618880.62
11  2022-12        682707.45
12  2023-01        950474.26
13  2023-02        841589.27
14  2023-03        859257.03
15  2023-04        925421.95
16  2023-05        892970.47
17  2023-06        851297.88
18  2023-07        909316.47
19  2023-08        924622.51
20  2023-09        932110.99
21  2023-10        914881.17
22  2023-11        891324.90
23  2023-12        906779.39
24  2024-01        927086.83
25  2024-02        805074.53
26  2024-03        949690.68
27  2024-04        868701.74
28  2024-05        879668.83
29  2024-06        880945.52
30  2024-07        924622.51
31  2024-08        956025.06
32  2024-09        890967.10
33  2024-10        916954.61
34  2024-11        881149.68
35  2024-12        950474.26
36  2025-01       1247417.86
37  2025-02       1127844.76
38  2025-03       1240171.67
39  2025-04       1129211.83
40  2025-05       1162661.53
41  2025-06       1155951.34
42  2025-07       1382026.96
43  2025-08       1383169.90
44  2025-09       1303985.42
45  2025-10       1997865.44
46  2025-11       1368343.69
47  2025-12       1425128.09

In [86]:
# Merge sales with store details
richards_stores = sales_df.merge(
    stores_df[['Store ID', 'Territory Manager']],
    on='Store ID',
    how='left')

# Filter manager name (precaution)
richards_stores = richards_stores[
    richards_stores['Territory Manager']
    .str.strip()
    .str.contains('Richards', case=False, na=False)]

# Converting dates
richards_stores['Transaction Date'] = pd.to_datetime(
    richards_stores['Transaction Date'])

# Month column
richards_stores['Month'] = (
    richards_stores['Transaction Date'].dt.to_period('M'))

# Monthly revenue
monthly_rev = (
    richards_stores
    .groupby('Month')['Sale Amount']
    .sum()
    .reset_index())

monthly_rev = monthly_rev.rename(
    columns={'Sale Amount': 'Monthly Revenue'})

#Display the output
display(monthly_rev)

      Month  Monthly Revenue
0   2022-01         40857.20
1   2022-02         52729.22
2   2022-03         49214.95
3   2022-04         55229.25
4   2022-05         49696.98
5   2022-06         45208.26
6   2022-07         48308.66
7   2022-08         49641.33
8   2022-09         47977.04
9   2022-10         50543.10
10  2022-11         41402.48
11  2022-12         49055.84
12  2023-01         72298.63
13  2023-02         45399.37
14  2023-03         67468.76
15  2023-04         76712.34
16  2023-05         74059.48
17  2023-06         68340.04
18  2023-07         63941.07
19  2023-08         60700.57
20  2023-09         69674.13
21  2023-10         64725.08
22  2023-11         65553.06
23  2023-12         78994.26
24  2024-01         49824.16
25  2024-02         64549.05
26  2024-03         80723.94
27  2024-04         70047.88
28  2024-05         70733.08
29  2024-06         61548.03
30  2024-07         60700.57
31  2024-08         71514.05
32  2024-09         62885.16
33  2024-10         70341.95
34  2024-11         74205.37
35  2024-12         72298.63
36  2025-01        101046.12
37  2025-02         95007.06
38  2025-03        101490.54
39  2025-04         81348.63
40  2025-05         85801.23
41  2025-06         87182.86
42  2025-07         91246.68
43  2025-08         98630.93
44  2025-09        109065.94
45  2025-10        168955.72
46  2025-11        105400.74
47  2025-12         95570.59

How would you rank the sales performance of each store in each sales territory? Which are the
top-performing stores?

In [87]:
# Merging of necessary sales information (sales_df & stores_df)
df = sales_df.merge(
    stores_df[['Store ID', 'Territory Manager', 'Store Location']],
    on='Store ID',
    how='left')

# Total rounded sales per store
store_perf = (
    df.groupby(['Territory Manager', 'Store ID', 'Store Location'])['Sale Amount']
    .sum()
    .reset_index()
    .rename(columns={'Sale Amount': 'Total Sales'}))

store_perf['Total Sales'] = store_perf['Total Sales'].round(2)

# Rank stores within each territory
store_perf['Rank'] = store_perf.groupby('Territory Manager')['Total Sales'] \
                               .rank(ascending=False, method='first')

# Sort
store_perf = store_perf.sort_values(['Rank', 'Territory Manager'])

# Display Output
display(store_perf)

        Territory Manager  Store ID  Store Location  Total Sales  Rank
17                Bo Heap       817       Worcester    602183.44   1.0
23            Ellen Lemon       870      New London    331116.76   1.0
31      Erbayne Middleton       823  South Portland    332611.76   1.0
36  Jeff "Howdy" Richards       905        Beaumont    637818.90   1.0
47               Jim Heck       705          Denver    917471.53   1.0
..                    ...       ...             ...          ...   ...
87              Miami Vue       837        Paterson     67112.57  16.0
3                 Bo Heap       803      Framingham    269375.91  17.0
60               Jim Heck       718     Wheat Ridge    280896.55  17.0
8                 Bo Heap       808          Lowell    266982.83  18.0
57               Jim Heck       715          Parker    279268.94  18.0

[111 rows x 5 columns]

Comparing the customer ID from the customer list data with the rewards ID from the sales data,
who were the top customers in each sales territory?

In [97]:
# Confirming the column names
store_sales.columns

Index(['Transaction Date', 'Store ID', 'RewardsID', 'Prod Num', 'Sale Amount'], dtype='object')

In [98]:
# Confirming the column names for customers_df
customers_df.columns

Index(['cust_id|date|time|name|email|phone|sms-opt-out '], dtype='object')

In [112]:
customers_df = pd.read_csv('customer_list.csv', sep='|')

# Extracting 'First Name' and 'Last Name' from the 'name' column
# Being that 'name' column contains 'First Name Last Name' format
customers_df[['First Name', 'Last Name']] = customers_df['name'].str.split(' ', n=1, expand=True)

# Merging sales information with store territory info
sales_territory = sales_df.merge(
    stores_df[['Store ID', 'Territory Manager']],
    on='Store ID',
    how='left')

# Merging to customers
full_data = sales_territory.merge(
    customers_df,
    left_on='RewardsID',
    right_on='cust_id',
    how='left')

# Total spending per customer per manager
customer_totals = (
    full_data.groupby(['Territory Manager', 'cust_id', 'First Name', 'Last Name'])['Sale Amount']
    .sum()
    .reset_index()
    .rename(columns={'Sale Amount': 'Total Sales'}))

# Ranking customers within every territory manager
customer_totals['Rank'] = customer_totals.groupby('Territory Manager')['Total Sales'] \
                               .rank(ascending=False, method='dense')

# Top customers
top_customers = customer_totals[customer_totals['Rank'] == 1]

# Display Output
display(top_customers)

          Territory Manager  cust_id First Name Last Name  Total Sales  Rank
245                 Bo Heap    292.0    Beverly   Crusher      4758.92   1.0
463             Ellen Lemon     18.0      Marie        S.      4388.87   1.0
948       Erbayne Middleton     89.0      Karen    Walker      3362.83   1.0
1587  Jeff "Howdy" Richards    344.0       Nate    Jacobs      5240.86   1.0
1950               Jim Heck    245.0     Gloria   Mendoza      7855.66   1.0
2229             Lana Ilana     47.0    Stanley        H.      4954.99   1.0
2800             Len Jensen    340.0        Jin      Kwon      1786.05   1.0
3197              Miami Vue    341.0        Ben     Linus      4810.66   1.0
3610           See Ellefson    300.0     Julian    Bashir      6039.32   1.0
3963           Shruti Reddy    180.0       Cole     Brown      7602.28   1.0

What is the number of transactions per month by product category in each assigned territory?
What is total sales revenue per month by category? What might this tell you about the most
popular products, and where could there be opportunity for growth?

In [116]:
# Build full dataset (making my joins)
df = sales_df.merge(
    stores_df[['Store ID', 'Territory Manager']],
    on='Store ID',
    how='left')

# Merging with product info
df = df.merge(
    products_df[['Prod Num', 'CategoryID']],
    on ='Prod Num',
    how='left')

# Merging with product category info
df = df.merge(
    products_categories_df[['CategoryID', 'Category']],
    on='CategoryID',
    how='left')

# Rename 'Category' to 'Category Name' to match the original intent
df = df.rename(columns={'Category': 'Category Name'})

# Month Column
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])
df['Month'] = df['Transaction Date'].dt.to_period('M')

# Total number of transactions per month by category/territory
transactions_per_month = (
    df.groupby(['Month', 'Territory Manager', 'Category Name'])['Sale Amount']
    .count()
    .reset_index()
    .rename(columns={'Sale Amount': 'Number of Transactions'}))

# Monthly Revenue

monthly_rev = (
    df.groupby(['Month', 'Territory Manager', 'Category Name'])['Sale Amount']
    .sum()
    .reset_index()
    .rename(columns={'Sale Amount': 'Monthly Revenue'}))

# Display Output
display(transactions_per_month, monthly_rev)

,Month,Territory Manager,Category Name,Number of Transactions
0,2022-01,Bo Heap,Apparel and Merchandise,664
1,2022-01,Bo Heap,Art Supplies,1023
2,2022-01,Bo Heap,Books (General),164
3,2022-01,Bo Heap,Stationery and Supplies,1166
4,2022-01,Bo Heap,Technology & Accessories,784
...,...,...,...,...
2875,2025-12,Shruti Reddy,Art Supplies,3927
2876,2025-12,Shruti Reddy,Books (General),1548
2877,2025-12,Shruti Reddy,Stationery and Supplies,5137
2878,2025-12,Shruti Reddy,Technology & Accessories,3773
2879,2025-12,Shruti Reddy,Textbooks,2750

        Month Territory Manager             Category Name  Monthly Revenue
0     2022-01           Bo Heap   Apparel and Merchandise         24065.20
1     2022-01           Bo Heap              Art Supplies         31947.19
2     2022-01           Bo Heap           Books (General)          4250.60
3     2022-01           Bo Heap   Stationery and Supplies         12519.32
4     2022-01           Bo Heap  Technology & Accessories        342649.16
...       ...               ...                       ...              ...
2875  2025-12      Shruti Reddy              Art Supplies        123992.55
2876  2025-12      Shruti Reddy           Books (General)         48137.92
2877  2025-12      Shruti Reddy   Stationery and Supplies         50737.83
2878  2025-12      Shruti Reddy  Technology & Accessories       1740433.80
2879  2025-12      Shruti Reddy                 Textbooks        471002.07

[2880 rows x 4 columns]

What is your recommendation for where to focus marketing attention in the next quarter?

*   Count of transactions; an emphasis on focus in demand and popularity on items.
*   Revenue/Profit Impact


*  Focus Recommendation:  Doubling down on high-demand categories in best performing territories