<a href="https://colab.research.google.com/github/elandverymuchnothing/Capstone_2/blob/main/lastname_sales_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
#My name Is Ariel Rollins; my Sales Manager is See Ellefson and New York is the state territory I will analyze.

In [47]:
#Data Analyis Library Import

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Below, 'Store Sales' are defined.

In [48]:
# Defining Store Sales

store_sales = pd.read_csv('StoreSales.csv')

display(store_sales)

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
0              1/1/2022       702        NaN   105349-M         8.00
1              1/1/2022       704        NaN   105350-T       144.00
2              1/1/2022       705        NaN   105351-M        44.00
3              1/1/2022       705        NaN   105352-M        47.61
4              1/1/2022       705        NaN   105353-A        20.36
...                 ...       ...        ...        ...          ...
335124       12/31/2025       909        NaN   105353-A        20.36
335125       12/31/2025       909      332.0   105364-S        17.70
335126       12/31/2025       910        NaN   105672-B        26.52
335127       12/31/2025       910        NaN   105653-M        11.00
335128       12/31/2025       910        NaN  105300-IT        77.81

[335129 rows x 5 columns]

In [49]:
# Imported Customer List
customers_df = pd.read_csv('customer_list.csv')
# Dataset information
customers_df.info()
display(customers_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    object
dtypes: object(1)
memory usage: 4.2+ KB

       cust_id|date|time|name|email|phone|sms-opt-out
0    1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1    2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2    3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3    4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4    5|2023-11-18|14:22:10|Joey|howyoudoing@central...
..                                                 ...
516  517|2024-02-15|11:30:30|Perry the Platypus|age...
517  518|2024-05-01|15:55:45|Baljeet|baljeet@danvil...
518  519|2023-03-05|09:20:00|Buford|buford@danville...
519  520|2023-05-18|13:45:15|Vanessa D.|vanessa@dan...
520  521|2023-08-01|18:10:30|Linda Flynn-Fletcher|l...

[521 rows x 1 columns]

In [50]:
# Imported Product Categories
products_categories_df = pd.read_csv('ProductCategories.csv')
# Dataset Information
products_categories_df.info
display(products_categories_df)

,CategoryID,Category,SubcategoryID,Subcategory
0,120,Technology & Accessories,120-tab,Tablets
1,120,Technology & Accessories,120-cal,Calculators
2,120,Technology & Accessories,120-sof,Software Download
3,120,Technology & Accessories,120-hea,Headphones
4,120,Technology & Accessories,120-ext,External Accessories
5,120,Technology & Accessories,120-cha,Chargers and Power Adapters
6,120,Technology & Accessories,120-lap,Laptops
7,130,Apparel and Merchandise,130-off,Office and Study Supplies
8,100,Textbooks,100-bus,Business & Economics
9,130,Apparel and Merchandise,130-clo,"Clothing (T-Shirts, Hoodies, and Jackets)"
10,130,Apparel and Merchandise,130-tec,Technology Accessories
11,115,Art Supplies,115-ske,Sketchbooks and Paper
12,125,Books (General),125-fic,Fiction
13,110,Stationery and Supplies,110-art,Art Supplies
14,100,Textbooks,100-mis,Miscellaneous Academic Topics
15,115,Art Supplies,115-kid,Kids Art Supplies
16,100,Textbooks,100-eng,Engineering & Technology
17,110,Stationery and Supplies,110-bin,Binders and Folders
18,100,Textbooks,100-hea,Health Sciences
19,100,Textbooks,100-tec,Technology and Computing
20,110,Stationery and Supplies,110-wri,Writing Instruments
21,100,Textbooks,100-soc,Social Sciences
22,110,Stationery and Supplies,110-des,Desk Accessories
23,100,Textbooks,100-lan,Language and Linguistics
24,130,Apparel and Merchandise,130-hom,Home and Decor
25,115,Art Supplies,115-mis,Miscellaneous Art Supplies
26,100,Textbooks,100-hum,Humanities
27,130,Apparel and Merchandise,130-hat,Hats and Caps
28,100,Textbooks,100-exa,Exam Prep and Study Guides
29,130,Apparel and Merchandise,130-mem,Memorabilia and Collectibles
30,115,Art Supplies,115-pai,Paint Brushes
31,130,Apparel and Merchandise,130-spo,Sports and Outdoor Gear
32,115,Art Supplies,115-scu,Sculpting Supplies
33,125,Books (General),125-stu,Study Guides
34,110,Stationery and Supplies,110-mis,Miscellaneous Supplies
35,115,Art Supplies,115-dra,Drawing and Sketching Tools
36,125,Books (General),125-non,Non-Fiction
37,110,Stationery and Supplies,110-pla,Planners and Calendars
38,115,Art Supplies,115-pai,Paints
39,115,Art Supplies,115-cal,Calligraphy and Lettering
40,110,Stationery and Supplies,110-not,Notebooks and Notepads
41,100,Textbooks,100-mat,Math and Statistics
42,110,Stationery and Supplies,110-adh,Adhesives and Tapes
43,110,Stationery and Supplies,110-org,Organization Supplies
44,100,Textbooks,100-sci,Science
45,130,Apparel and Merchandise,130-acc,Accessories
46,115,Art Supplies,115-cut,Cutting and Measuring Tools
47,110,Stationery and Supplies,110-pen,Pencils and Erasers
48,110,Stationery and Supplies,110-pap,Paper Products
49,125,Books (General),125-ref,Reference Materials
50,115,Art Supplies,115-pal,Palettes and Mixing Tools
51,115,Art Supplies,115-eas,Easels and Storage

In [51]:
# Import Products.csv
products_df = pd.read_csv('Products (1).csv')
# Dataset information
products_df.info()
display(products_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

      Prod Num                               Product  CategoryID SubcategoryID
0    105248-IT                      TCL NXTPAPER 10s         120       120-tab
1    105249-IT         Dell Latitude 7320 Detachable         120       120-tab
2    105250-IT                            Realme Pad         120       120-tab
3    105251-IT                    Lenovo Tab P12 Pro         120       120-tab
4    105252-IT               Microsoft Surface Pro 9         120       120-tab
..         ...                                   ...         ...           ...
664   105912-T               Networking Fundamentals         100       100-tec
665   105913-T             Introduction to Databases         100       100-tec
666  105914-IT    SanDisk Extreme Portable SSD (1TB)         120       120-ext
667   105915-M  LTCA Year Up Spiral Notebook (Black)         130       130-off
668   105916-M       LTCA Year Up Sunglasses (Black)         130       130-acc

[669 rows x 4 columns]

In [52]:
# Import Store Sales
sales_df = pd.read_csv('StoreSales.csv')
# View dataset information
sales_df.info()
display(sales_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
0              1/1/2022       702        NaN   105349-M         8.00
1              1/1/2022       704        NaN   105350-T       144.00
2              1/1/2022       705        NaN   105351-M        44.00
3              1/1/2022       705        NaN   105352-M        47.61
4              1/1/2022       705        NaN   105353-A        20.36
...                 ...       ...        ...        ...          ...
335124       12/31/2025       909        NaN   105353-A        20.36
335125       12/31/2025       909      332.0   105364-S        17.70
335126       12/31/2025       910        NaN   105672-B        26.52
335127       12/31/2025       910        NaN   105653-M        11.00
335128       12/31/2025       910        NaN  105300-IT        77.81

[335129 rows x 5 columns]

In [53]:
# Import Store Details
stores_df = pd.read_csv('StoreDetail.csv')
# Dataset information
stores_df.info()
display(stores_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

,Store Location,State,Store ID,Territory Manager,Region,Region Director
0,Aurora,Colorado,701,Jim Heck,West,Cassie Chambers
1,Berthoud,Colorado,702,Jim Heck,West,Cassie Chambers
2,Boulder,Colorado,703,Jim Heck,West,Cassie Chambers
3,Castle Rock,Colorado,704,Jim Heck,West,Cassie Chambers
4,Denver,Colorado,705,Jim Heck,West,Cassie Chambers
...,...,...,...,...,...,...
106,Dallas,Texas,907,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
107,Denton,Texas,908,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
108,Desoto,Texas,909,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
109,Fort Worth,Texas,910,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
110,Georgetown,Texas,911,"Jeff ""Howdy"" Richards",South,Andy Gisselquist

Who are the territory managers for the sales territories assigned? What are the store IDs and cities for the stores in each assigned sales territory?

In [70]:
# Stores for See Ellefson
see_stores = stores_df[
    stores_df["Territory Manager"] == "See Ellefson"]

# Displaying relevant columns
see_stores[
    ["Territory Manager", "Store ID", "Store Location"]]

#Store IDs range from 840-851 in numerical order, smallest to largest.
#The city locations for Stores 840-851 are listed as Albany, Buffalo, Elmira, Ithaca, Oswego, Plattsburgh, Poestenkill, Rochester, Syracuse, Brooklyn, New York, & Queens.

# Stores for Jeff "Howdy" Richards

richards_stores = stores_df[
    stores_df["Territory Manager"] == 'Jeff "Howdy" Richards']

# Displaying relevant columns
richards_stores[
    ["Territory Manager", "Store ID", "Store Location"]]

print("Stores for both See Ellefson's and Jeff 'Howdy' Richards'")
display(see_stores, richards_stores)

Stores for both See Ellefson's and Jeff 'Howdy' Richards'

   Store Location     State  Store ID Territory Manager Region Region Director
86         Albany  New York       840      See Ellefson   East      Ana Jilani
87        Buffalo  New York       841      See Ellefson   East      Ana Jilani
88         Elmira  New York       842      See Ellefson   East      Ana Jilani
89         Ithaca  New York       843      See Ellefson   East      Ana Jilani
90         Oswego  New York       844      See Ellefson   East      Ana Jilani
91    Plattsburgh  New York       845      See Ellefson   East      Ana Jilani
92    Poestenkill  New York       846      See Ellefson   East      Ana Jilani
93      Rochester  New York       847      See Ellefson   East      Ana Jilani
94       Syracuse  New York       848      See Ellefson   East      Ana Jilani
95       Brooklyn  New York       849      See Ellefson   East      Ana Jilani
96       New York  New York       850      See Ellefson   East      Ana Jilani
97         Queens  New York       851      See Ellefson   East      Ana Jilani

,Store Location,State,Store ID,Territory Manager,Region,Region Director
100,Arlington,Texas,901,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
101,Austin,Texas,902,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
102,Bacliff,Texas,903,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
103,Baytown,Texas,904,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
104,Beaumont,Texas,905,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
105,Cedar Park,Texas,906,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
106,Dallas,Texas,907,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
107,Denton,Texas,908,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
108,Desoto,Texas,909,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
109,Fort Worth,Texas,910,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
110,Georgetown,Texas,911,"Jeff ""Howdy"" Richards",South,Andy Gisselquist

What is monthly total revenue for in-store sales in each of the two sales territories, over the full
period covered by the data?

In [ ]:
current_sales = sales_df.copy()
# Convert the date and create the 'Month' column


current_sales['Transaction Date'] = pd.to_datetime(current_sales['Transaction Date'])
current_sales['Month'] = current_sales['Transaction Date'].dt.to_period('M')
current_sales['Year'] = current_sales['Transaction Date'].dt.year

# Group by the month and sum the sales amount

monthly_rev = (current_sales
               .groupby('Month')['Sale Amount']
               .sum()
               .reset_index())

monthly_rev = monthly_rev.rename (columns = {'Sale Amount': 'Monthly Revenue'})
display(monthly_rev)